web:
  build: .
  volumes:
    - .:/app
    - ~/.bash_history:/root/.bash_history
  ports:
    - 8080:8080
  environment:
    BUNDLE_PATH: /bundle_cache
    CIRCLE_CI_AUTH_TOKEN: 11db2e7b773a5228e32947d0958e6a3368031fd1
  command: /bin/bash -c 'bundle exec dashing start -p 8080'
  volumes_from:
    - bundle_cache

bundle_cache:
  image: busybox
  volumes:
    - /bundle_cache
